# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl }:

self: super: {
  "tsplib95" = super.buildPythonPackage rec {
    pname = "tsplib95";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/2b/b1932d3674758ec5f49afa72d4519334a5ac2aac4d96cfd416eb872a1959/tsplib95-0.7.1-py2.py3-none-any.whl";
      sha256 = "114iwmx1a7na0rhqmhjd5raiws5jlmx4g4dl6hhsdaiv567670f4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      pkgs.python3Packages.click
      pkgs.python3Packages.deprecated
      pkgs.python3Packages.networkx
      pkgs.python3Packages.tabulate
    ];
  };
}
